<a href="https://colab.research.google.com/github/Bhagya-Navodyani/Intelligent_Fish_Storage-ML/blob/main/notebook/Fish_Storage_ML_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Dataset Loading

# Intelligent Fish Storage ML Pipeline

**Research Section:** Intelligent Fish Storage Quality Monitoring and Remaining Shelf-Life Prediction Using IoT and Machine Learning

This notebook contains the preprocessing and machine learning workflow for sensor data collected using the ESP32-S3 fish-storage monitoring prototype.

In [23]:
import pandas as pd
import numpy as np

# CSV file already uploaded to Colab
filename = "/content/Final_csv.csv"

# Read CSV
df_raw = pd.read_csv(filename)

print("Uploaded file:", filename)
print("Rows, Columns:", df_raw.shape)

print("\nColumns:")
print(df_raw.columns.tolist())

df_raw.head()

Uploaded file: /content/Final_csv.csv
Rows, Columns: (10465, 20)

Columns:
['pc_timestamp', 'trial_id', 'fish_species', 'record_type', 'elapsed_sec', 'storage_temp_c', 'air_temp_c', 'humidity_pct', 'distance_cm', 'gas_raw', 'reed_raw', 'lid', 'current_lid_open_sec', 'total_lid_open_sec', 'lid_open_count', 'storage_time_hours', 'temp_difference_c', 'lid_open_ratio', 'lid_open_rate_per_hour', 'avg_lid_open_duration_sec']

,pc_timestamp,trial_id,fish_species,record_type,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,lid,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
0,2026-09-29 10:02:23,TRIAL_20260929_100223,Linna,START,0,0.25,28.5,84.8,28.37,835,0,OPEN,0,0,1,0.0000,28.25,0.0,0.0,0.0
1,2026-09-29 10:02:53,TRIAL_20260929_100223,Linna,PERIODIC,30,0.25,28.3,84.1,28.38,835,0,OPEN,30,30,1,0.0083,28.05,1.0,0.0,30.0
2,2026-09-29 10:03:23,TRIAL_20260929_100223,Linna,PERIODIC,60,0.25,28.2,86.0,28.38,835,0,OPEN,60,60,1,0.0167,27.95,1.0,0.0,60.0
3,2026-09-29 10:03:53,TRIAL_20260929_100223,Linna,PERIODIC,90,0.25,28.1,86.0,28.37,835,0,OPEN,90,90,1,0.0250,27.85,1.0,0.0,90.0
4,2026-09-29 10:04:23,TRIAL_20260929_100223,Linna,PERIODIC,120,0.25,28.0,86.4,29.26,835,0,OPEN,120,120,1,0.0333,27.75,1.0,0.0,120.0

## 2. Dataset Audit

In [24]:
# Create a working copy while preserving the loaded dataset
df = df_raw.copy()

# Convert timestamp to datetime format
df["pc_timestamp"] = pd.to_datetime(
    df["pc_timestamp"],
    errors="coerce"
)

# Sort records chronologically
df = df.sort_values("pc_timestamp").reset_index(drop=True)

# Dataset summary
print("Total rows:", len(df))
print("Total columns:", len(df.columns))

print("\nMissing values in each column:")
print(df.isnull().sum())

print("\nFirst timestamp:", df["pc_timestamp"].min())
print("Last timestamp :", df["pc_timestamp"].max())

display(df.head())

Total rows: 10465
Total columns: 20

Missing values in each column:
pc_timestamp                   0
trial_id                       0
fish_species                   0
record_type                    0
elapsed_sec                    0
storage_temp_c                 0
air_temp_c                     0
humidity_pct                   0
distance_cm                  311
gas_raw                        0
reed_raw                       0
lid                            0
current_lid_open_sec           0
total_lid_open_sec             0
lid_open_count                 0
storage_time_hours             0
temp_difference_c              0
lid_open_ratio                 0
lid_open_rate_per_hour         0
avg_lid_open_duration_sec      0
dtype: int64

First timestamp: 2026-09-29 10:02:23
Last timestamp : 2026-10-03 00:22:24

,pc_timestamp,trial_id,fish_species,record_type,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,lid,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
0,2026-09-29 10:02:23,TRIAL_20260929_100223,Linna,START,0,0.25,28.5,84.8,28.37,835,0,OPEN,0,0,1,0.0000,28.25,0.0,0.0,0.0
1,2026-09-29 10:02:53,TRIAL_20260929_100223,Linna,PERIODIC,30,0.25,28.3,84.1,28.38,835,0,OPEN,30,30,1,0.0083,28.05,1.0,0.0,30.0
2,2026-09-29 10:03:23,TRIAL_20260929_100223,Linna,PERIODIC,60,0.25,28.2,86.0,28.38,835,0,OPEN,60,60,1,0.0167,27.95,1.0,0.0,60.0
3,2026-09-29 10:03:53,TRIAL_20260929_100223,Linna,PERIODIC,90,0.25,28.1,86.0,28.37,835,0,OPEN,90,90,1,0.0250,27.85,1.0,0.0,90.0
4,2026-09-29 10:04:23,TRIAL_20260929_100223,Linna,PERIODIC,120,0.25,28.0,86.4,29.26,835,0,OPEN,120,120,1,0.0333,27.75,1.0,0.0,120.0

In [25]:
# Check exact duplicate rows
duplicate_count = df.duplicated().sum()

print("Exact duplicate rows:", duplicate_count)

# Display basic numerical statistics
display(df.describe())

Exact duplicate rows: 0

,pc_timestamp,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
count,10465,10465.000000,10465.000000,10465.000000,10465.000000,10154.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000
mean,2026-10-01 05:07:33.561681664,155110.561682,1.828822,17.700554,81.426393,29.699733,473.731295,0.944386,19.286670,9724.143717,35.257047,43.086266,15.871732,0.080273,1.124134,265.053454
min,2026-09-29 10:02:23,0.000000,-0.250000,13.000000,57.400000,4.720000,200.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.900000,0.000000,0.000000,0.000000
25%,2026-09-30 07:29:29,77226.000000,0.000000,15.300000,73.300000,27.870000,275.000000,1.000000,0.000000,6551.000000,26.000000,21.451700,13.800000,0.054727,0.679600,266.136000
50%,2026-10-01 05:06:26,155043.000000,0.500000,17.300000,80.000000,28.710000,393.000000,1.000000,0.000000,10981.000000,37.000000,43.067500,15.650000,0.070716,0.837200,275.807000
75%,2026-10-02 02:48:26,233163.000000,1.500000,19.300000,89.200000,30.410000,627.000000,1.000000,0.000000,12762.000000,43.000000,64.767500,17.600000,0.080717,1.127900,296.784000
max,2026-10-03 00:22:24,310801.000000,23.500000,28.500000,100.000000,63.830000,1761.000000,1.000000,2278.000000,15721.000000,57.000000,86.333600,28.250000,1.000000,6.818200,630.000000
std,NaN,89930.812406,3.498060,3.010103,9.844427,3.760690,234.341593,0.229186,129.840186,4112.439112,12.845562,24.980780,3.476105,0.065577,0.872750,53.509667

### Initial Audit Findings

- The dataset contains 10,465 sensor observations.
- No exact duplicate rows were detected.
- The records are arranged chronologically using `pc_timestamp`.
- The `distance_cm` feature contains 311 missing values.
- The storage-temperature and gas-sensor columns require further anomaly investigation before model training.
- Sensor-quality issues will be handled during the preprocessing stage without modifying the original dataset.

In [26]:
# Check important sensor data characteristics

zero_temp_count = (df["storage_temp_c"] == 0).sum()
high_gas_count = (df["gas_raw"] > 1000).sum()
missing_distance_count = df["distance_cm"].isnull().sum()
missing_temp_count = df["storage_temp_c"].isnull().sum()

print("storage_temp_c = 0°C readings:", zero_temp_count)
print("Missing storage_temp_c readings:", missing_temp_count)
print("gas_raw > 1000 readings:", high_gas_count)
print("Missing distance_cm rows:", missing_distance_count)

storage_temp_c = 0°C readings: 3128
Missing storage_temp_c readings: 0
gas_raw > 1000 readings: 14
Missing distance_cm rows: 311

## 3. Data Preprocessing

This section prepares the audited sensor dataset for machine learning while preserving the original measurements and documenting each preprocessing step.

### 3.2 Storage Temperature Validation

In [27]:
# Identify zero storage-temperature readings

zero_temp = df[df["storage_temp_c"] == 0].copy()

print("Total zero-temperature rows:", len(zero_temp))

print("\nFirst zero-temperature readings:")
display(
    zero_temp[
        ["pc_timestamp", "elapsed_sec", "storage_temp_c", "air_temp_c"]
    ].head(10)
)

print("\nLast zero-temperature readings:")
display(
    zero_temp[
        ["pc_timestamp", "elapsed_sec", "storage_temp_c", "air_temp_c"]
    ].tail(10)
)

Total zero-temperature rows: 3128

First zero-temperature readings:

          pc_timestamp  elapsed_sec  storage_temp_c  air_temp_c
12 2026-09-29 10:08:23          360             0.0        27.5
17 2026-09-29 10:10:53          510             0.0        26.3
18 2026-09-29 10:11:23          540             0.0        26.1
19 2026-09-29 10:11:53          570             0.0        25.9
20 2026-09-29 10:12:23          600             0.0        25.8
21 2026-09-29 10:12:53          630             0.0        25.6
22 2026-09-29 10:12:55          632             0.0        25.6
23 2026-09-29 10:13:23          660             0.0        25.2
24 2026-09-29 10:13:53          690             0.0        24.7
25 2026-09-29 10:14:23          720             0.0        24.2

Last zero-temperature readings:

            pc_timestamp  elapsed_sec  storage_temp_c  air_temp_c
9506 2026-10-02 16:26:24       282241             0.0        19.9
9508 2026-10-02 16:27:24       282301             0.0        19.9
9510 2026-10-02 16:28:24       282361             0.0        19.9
9511 2026-10-02 16:28:54       282391             0.0        19.9
9517 2026-10-02 16:31:54       282571             0.0        20.0
9518 2026-10-02 16:32:24       282601             0.0        20.0
9521 2026-10-02 16:33:54       282691             0.0        20.1
9528 2026-10-02 16:37:24       282901             0.0        20.1
9533 2026-10-02 16:39:54       283051             0.0        20.2
9536 2026-10-02 16:41:24       283141             0.0        20.2

In [28]:
# Validate storage-temperature measurements

zero_temp_count = (df["storage_temp_c"] == 0).sum()
missing_temp_count = df["storage_temp_c"].isnull().sum()

print("Valid 0°C storage-temperature readings:", zero_temp_count)
print("Missing storage-temperature readings:", missing_temp_count)

Valid 0°C storage-temperature readings: 3128
Missing storage-temperature readings: 0

### 3.3 Gas Sensor Quality Investigation

Gas readings are checked for statistical outliers while preserving the original `gas_raw` values.

In [29]:
# Detect gas outliers using the IQR method

q1 = df["gas_raw"].quantile(0.25)
q3 = df["gas_raw"].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

gas_outlier_mask = (
    (df["gas_raw"] < lower_bound) |
    (df["gas_raw"] > upper_bound)
)

print("Gas Q1:", q1)
print("Gas Q3:", q3)
print("IQR:", iqr)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Gas outlier rows:", gas_outlier_mask.sum())

display(
    df.loc[
        gas_outlier_mask,
        ["pc_timestamp", "gas_raw"]
    ]
)

Gas Q1: 275.0
Gas Q3: 627.0
IQR: 352.0
Lower bound: -253.0
Upper bound: 1155.0
Gas outlier rows: 11

            pc_timestamp  gas_raw
1422 2026-09-29 21:35:40     1691
2405 2026-09-30 05:45:02     1679
2406 2026-09-30 05:45:09     1651
2407 2026-09-30 05:45:38     1614
2408 2026-09-30 05:45:39     1613
2427 2026-09-30 05:53:09     1761
2432 2026-09-30 05:55:39     1527
3372 2026-09-30 13:44:58     1497
3376 2026-09-30 13:46:58     1564
3377 2026-09-30 13:47:28     1531
4332 2026-09-30 21:37:57     1568

In [30]:
print("Raw gas mean:", df["gas_raw"].mean())
print(
    "Mean without statistical outliers:",
    df.loc[~gas_outlier_mask, "gas_raw"].mean()
)

Raw gas mean: 473.73129479216436
Mean without statistical outliers: 472.53701932274726

### Gas Sensor Preprocessing

Statistical gas outliers are excluded from gas-based ML features while preserving the original `gas_raw` measurements.

In [31]:
# Preserve original gas readings for ML preprocessing
df["gas_clean"] = df["gas_raw"].astype(float)

# Mark IQR-detected gas outliers as missing for ML use
df.loc[gas_outlier_mask, "gas_clean"] = np.nan

print("Original gas rows:", len(df))
print("Gas outliers excluded:", gas_outlier_mask.sum())
print("Valid gas values for ML:", df["gas_clean"].notna().sum())

Original gas rows: 10465
Gas outliers excluded: 11
Valid gas values for ML: 10454

### 3.4 Gas Feature Engineering

`gas_delta` measures change from the initial gas baseline, while `gas_rolling_median` reduces short-term sensor noise.

In [32]:
# Gas feature engineering

# Smooth short-term gas fluctuations
df["gas_rolling_median"] = (
    df["gas_clean"]
    .rolling(window=5, min_periods=1)
    .median()
)

# Keep outlier positions excluded
df.loc[
    gas_outlier_mask,
    "gas_rolling_median"
] = np.nan

print("Missing gas_clean values:",
      df["gas_clean"].isnull().sum())

print("Missing gas_rolling_median values:",
      df["gas_rolling_median"].isnull().sum())

Missing gas_clean values: 11
Missing gas_rolling_median values: 11

In [33]:
candidate_features = [
    "storage_time_hours",
    "storage_temp_c",
    "air_temp_c",
    "humidity_pct",
    "temp_difference_c",
    "lid_open_ratio",
    "lid_open_rate_per_hour",
    "avg_lid_open_duration_sec",
    "gas_clean",
    "gas_rolling_median"
]

print("Candidate ML features:\n")

for feature in candidate_features:
    print("-", feature)

print("\nMissing values in candidate features:\n")
print(df[candidate_features].isnull().sum())

Candidate ML features:

- storage_time_hours
- storage_temp_c
- air_temp_c
- humidity_pct
- temp_difference_c
- lid_open_ratio
- lid_open_rate_per_hour
- avg_lid_open_duration_sec
- gas_clean
- gas_rolling_median

Missing values in candidate features:

storage_time_hours            0
storage_temp_c                0
air_temp_c                    0
humidity_pct                  0
temp_difference_c             0
lid_open_ratio                0
lid_open_rate_per_hour        0
avg_lid_open_duration_sec     0
gas_clean                    11
gas_rolling_median           11
dtype: int64

## 4. Time-Block Preparation

Because consecutive sensor readings are highly correlated, individual rows are not randomly split into training, validation, and testing sets.

The continuous time-series is first divided into 30-minute blocks. Four consecutive 30-minute blocks are then combined into one non-overlapping 2-hour temporal group.

These whole temporal groups will later be randomly assigned to the training, validation, and testing sets after the ground-truth freshness labels are prepared.

In [34]:
# Create 30-minute temporal blocks
# 30 minutes = 1800 seconds

df["block_30min"] = (
    df["elapsed_sec"] // 1800
).astype(int)

# Combine every 4 consecutive 30-minute blocks
# into one 2-hour temporal group
df["group_2h"] = (
    df["block_30min"] // 4
).astype(int)

print("Total 30-minute blocks:", df["block_30min"].nunique())
print("Total 2-hour groups:", df["group_2h"].nunique())

display(
    df[
        [
            "pc_timestamp",
            "elapsed_sec",
            "block_30min",
            "group_2h"
        ]
    ].head(20)
)

Total 30-minute blocks: 173
Total 2-hour groups: 44

          pc_timestamp  elapsed_sec  block_30min  group_2h
0  2026-09-29 10:02:23            0            0         0
1  2026-09-29 10:02:53           30            0         0
2  2026-09-29 10:03:23           60            0         0
3  2026-09-29 10:03:53           90            0         0
4  2026-09-29 10:04:23          120            0         0
5  2026-09-29 10:04:53          150            0         0
6  2026-09-29 10:05:23          180            0         0
7  2026-09-29 10:05:53          210            0         0
8  2026-09-29 10:06:23          240            0         0
9  2026-09-29 10:06:53          270            0         0
10 2026-09-29 10:07:23          300            0         0
11 2026-09-29 10:07:53          330            0         0
12 2026-09-29 10:08:23          360            0         0
13 2026-09-29 10:08:53          390            0         0
14 2026-09-29 10:09:23          420            0         0
15 2026-09-29 10:09:53          450            0         0
16 2026-09-29 10:10:23          480            0         0
17 2026-09-29 10:10:53          510            0         0
18 2026-09-29 10:11:23          540            0         0
19 2026-09-29 10:11:53          570            0         0

In [35]:
# Summarize each 2-hour temporal group

group_summary = (
    df.groupby("group_2h")
    .agg(
        start_time=("pc_timestamp", "min"),
        end_time=("pc_timestamp", "max"),
        rows=("pc_timestamp", "size"),
        first_block=("block_30min", "min"),
        last_block=("block_30min", "max")
    )
    .reset_index()
)

display(group_summary.head(10))

print("Total temporal groups:", len(group_summary))

,group_2h,start_time,end_time,rows,first_block,last_block
0,0,2026-09-29 10:02:23,2026-09-29 12:01:53,261,0,3
1,1,2026-09-29 12:02:23,2026-09-29 14:02:10,241,4,7
2,2,2026-09-29 14:02:40,2026-09-29 16:02:10,244,8,11
3,3,2026-09-29 16:02:40,2026-09-29 18:02:10,242,12,15
4,4,2026-09-29 18:02:40,2026-09-29 20:02:10,242,16,19
5,5,2026-09-29 20:02:40,2026-09-29 22:02:09,247,20,23
6,6,2026-09-29 22:02:39,2026-09-30 00:02:09,242,24,27
7,7,2026-09-30 00:02:39,2026-09-30 02:02:09,240,28,31
8,8,2026-09-30 02:02:39,2026-09-30 04:02:09,240,32,35
9,9,2026-09-30 04:02:39,2026-09-30 06:01:59,243,36,39

Total temporal groups: 44

## 5. Ground-Truth Freshness Labeling

Freshness labels will be assigned only using independently recorded ground-truth observations.

In [36]:
# Confirmed freshness checkpoints

confirmed_checkpoints = pd.DataFrame({
    "group_2h": [0, 29, 43],
    "freshness_label": ["LOW", "MEDIUM", "HIGH"]
})

df["freshness_label"] = pd.NA

for _, row in confirmed_checkpoints.iterrows():
    df.loc[
        df["group_2h"] == row["group_2h"],
        "freshness_label"
    ] = row["freshness_label"]

display(confirmed_checkpoints)

print("\nLabel distribution:")
print(df["freshness_label"].value_counts(dropna=False))

   group_2h freshness_label
0         0             LOW
1        29          MEDIUM
2        43            HIGH

Label distribution:
freshness_label
<NA>      9921
LOW        261
MEDIUM     242
HIGH        41
Name: count, dtype: int64

In [37]:
# Check confirmed labeled groups

label_summary = (
    df.dropna(subset=["freshness_label"])
      .groupby(["group_2h", "freshness_label"])
      .agg(
          start_time=("pc_timestamp", "min"),
          end_time=("pc_timestamp", "max"),
          rows=("pc_timestamp", "size")
      )
      .reset_index()
)

display(label_summary)

   group_2h freshness_label          start_time            end_time  rows
0         0             LOW 2026-09-29 10:02:23 2026-09-29 12:01:53   261
1        29          MEDIUM 2026-10-01 20:02:26 2026-10-01 22:01:56   242
2        43            HIGH 2026-10-03 00:02:23 2026-10-03 00:22:24    41

In [38]:
# Check freshness-label coverage by temporal group

group_label_status = (
    df.groupby("group_2h")
      .agg(
          start_time=("pc_timestamp", "min"),
          end_time=("pc_timestamp", "max"),
          rows=("pc_timestamp", "size"),
          freshness_label=("freshness_label", "first")
      )
      .reset_index()
)

group_label_status["label_status"] = (
    group_label_status["freshness_label"]
    .notna()
    .map({True: "LABELED", False: "UNLABELED"})
)

print("Total temporal groups:", len(group_label_status))
print("\nGroup label status:")
print(group_label_status["label_status"].value_counts())

display(group_label_status)

Total temporal groups: 44

Group label status:
label_status
UNLABELED    41
LABELED       3
Name: count, dtype: int64

,group_2h,start_time,end_time,rows,freshness_label,label_status
0,0,2026-09-29 10:02:23,2026-09-29 12:01:53,261,LOW,LABELED
1,1,2026-09-29 12:02:23,2026-09-29 14:02:10,241,None,UNLABELED
2,2,2026-09-29 14:02:40,2026-09-29 16:02:10,244,None,UNLABELED
3,3,2026-09-29 16:02:40,2026-09-29 18:02:10,242,None,UNLABELED
4,4,2026-09-29 18:02:40,2026-09-29 20:02:10,242,None,UNLABELED
5,5,2026-09-29 20:02:40,2026-09-29 22:02:09,247,None,UNLABELED
6,6,2026-09-29 22:02:39,2026-09-30 00:02:09,242,None,UNLABELED
7,7,2026-09-30 00:02:39,2026-09-30 02:02:09,240,None,UNLABELED
8,8,2026-09-30 02:02:39,2026-09-30 04:02:09,240,None,UNLABELED
9,9,2026-09-30 04:02:39,2026-09-30 06:01:59,243,None,UNLABELED
10,10,2026-09-30 06:02:29,2026-09-30 08:01:59,240,None,UNLABELED
11,11,2026-09-30 08:02:29,2026-09-30 10:01:58,242,None,UNLABELED
12,12,2026-09-30 10:02:28,2026-09-30 12:01:58,242,None,UNLABELED
13,13,2026-09-30 12:02:28,2026-09-30 14:01:58,242,None,UNLABELED
14,14,2026-09-30 14:02:28,2026-09-30 16:01:58,240,None,UNLABELED
15,15,2026-09-30 16:02:28,2026-09-30 18:01:57,248,None,UNLABELED
16,16,2026-09-30 18:02:27,2026-09-30 20:01:57,244,None,UNLABELED
17,17,2026-09-30 20:02:27,2026-09-30 22:01:57,242,None,UNLABELED
18,18,2026-09-30 22:02:27,2026-10-01 00:01:57,242,None,UNLABELED
19,19,2026-10-01 00:02:27,2026-10-01 02:01:57,240,None,UNLABELED
20,20,2026-10-01 02:02:27,2026-10-01 04:01:56,240,None,UNLABELED
21,21,2026-10-01 04:02:26,2026-10-01 06:01:56,242,None,UNLABELED
22,22,2026-10-01 06:02:26,2026-10-01 08:01:56,240,None,UNLABELED
23,23,2026-10-01 08:02:26,2026-10-01 10:01:56,240,None,UNLABELED
24,24,2026-10-01 10:02:26,2026-10-01 12:01:55,242,None,UNLABELED
25,25,2026-10-01 12:02:25,2026-10-01 14:01:57,242,None,UNLABELED
26,26,2026-10-01 14:02:27,2026-10-01 16:01:57,242,None,UNLABELED
27,27,2026-10-01 16:02:27,2026-10-01 18:01:57,240,None,UNLABELED
28,28,2026-10-01 18:02:27,2026-10-01 20:01:56,240,None,UNLABELED
29,29,2026-10-01 20:02:26,2026-10-01 22:01:56,242,MEDIUM,LABELED
30,30,2026-10-01 22:02:26,2026-10-02 00:01:56,242,None,UNLABELED
31,31,2026-10-02 00:02:26,2026-10-02 02:01:56,240,None,UNLABELED
32,32,2026-10-02 02:02:26,2026-10-02 04:01:56,244,None,UNLABELED
33,33,2026-10-02 04:02:26,2026-10-02 06:01:55,240,None,UNLABELED
34,34,2026-10-02 06:02:25,2026-10-02 08:01:55,240,None,UNLABELED
35,35,2026-10-02 08:02:25,2026-10-02 10:01:55,240,None,UNLABELED
36,36,2026-10-02 10:02:25,2026-10-02 12:01:55,248,None,UNLABELED
37,37,2026-10-02 12:02:25,2026-10-02 14:01:54,244,None,UNLABELED
38,38,2026-10-02 14:02:24,2026-10-02 16:01:54,246,None,UNLABELED
39,39,2026-10-02 16:02:24,2026-10-02 18:01:54,242,None,UNLABELED
40,40,2026-10-02 18:02:24,2026-10-02 20:01:54,244,None,UNLABELED
41,41,2026-10-02 20:02:24,2026-10-02 22:01:53,240,None,UNLABELED
42,42,2026-10-02 22:02:23,2026-10-03 00:01:53,240,None,UNLABELED
43,43,2026-10-03 00:02:23,2026-10-03 00:22:24,41,HIGH,LABELED

In [39]:
# Summarize sensor features for confirmed freshness labels

confirmed_feature_summary = (
    df.dropna(subset=["freshness_label"])
      .groupby("freshness_label")[candidate_features]
      .median()
      .round(2)
)

display(confirmed_feature_summary)

,storage_time_hours,storage_temp_c,air_temp_c,humidity_pct,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec,gas_clean,gas_rolling_median
freshness_label,,,,,,,,,,
HIGH,86.17,23.25,25.3,98.4,2.05,0.05,0.65,275.81,613.0,611.0
LOW,1.01,0.00,18.0,100.0,18.00,0.28,5.26,178.00,846.0,846.0
MEDIUM,58.99,0.00,14.8,79.9,14.50,0.06,0.69,302.71,245.0,245.0

In [40]:
# Check gas trend across temporal groups

gas_group_summary = (
    df.groupby("group_2h")
      .agg(
          start_time=("pc_timestamp", "min"),
          end_time=("pc_timestamp", "max"),
          gas_median=("gas_clean", "median"),
          gas_min=("gas_clean", "min"),
          gas_max=("gas_clean", "max")
      )
      .reset_index()
)

display(gas_group_summary)

,group_2h,start_time,end_time,gas_median,gas_min,gas_max
0,0,2026-09-29 10:02:23,2026-09-29 12:01:53,846.0,835.0,980.0
1,1,2026-09-29 12:02:23,2026-09-29 14:02:10,858.0,844.0,864.0
2,2,2026-09-29 14:02:40,2026-09-29 16:02:10,868.5,861.0,875.0
3,3,2026-09-29 16:02:40,2026-09-29 18:02:10,881.0,875.0,887.0
4,4,2026-09-29 18:02:40,2026-09-29 20:02:10,890.0,842.0,985.0
5,5,2026-09-29 20:02:40,2026-09-29 22:02:09,880.0,799.0,1031.0
6,6,2026-09-29 22:02:39,2026-09-30 00:02:09,799.5,781.0,844.0
7,7,2026-09-30 00:02:39,2026-09-30 02:02:09,798.0,792.0,804.0
8,8,2026-09-30 02:02:39,2026-09-30 04:02:09,800.0,793.0,807.0
9,9,2026-09-30 04:02:39,2026-09-30 06:01:59,807.0,628.0,1017.0
10,10,2026-09-30 06:02:29,2026-09-30 08:01:59,654.0,584.0,918.0
11,11,2026-09-30 08:02:29,2026-09-30 10:01:58,527.0,489.0,627.0
12,12,2026-09-30 10:02:28,2026-09-30 12:01:58,479.0,435.0,572.0
13,13,2026-09-30 12:02:28,2026-09-30 14:01:58,475.0,427.0,744.0
14,14,2026-09-30 14:02:28,2026-09-30 16:01:58,486.0,441.0,588.0
15,15,2026-09-30 16:02:28,2026-09-30 18:01:57,506.0,413.0,637.0
16,16,2026-09-30 18:02:27,2026-09-30 20:01:57,499.5,459.0,639.0
17,17,2026-09-30 20:02:27,2026-09-30 22:01:57,485.0,329.0,807.0
18,18,2026-09-30 22:02:27,2026-10-01 00:01:57,329.0,275.0,447.0
19,19,2026-10-01 00:02:27,2026-10-01 02:01:57,279.0,269.0,295.0
20,20,2026-10-01 02:02:27,2026-10-01 04:01:56,308.0,293.0,317.0
21,21,2026-10-01 04:02:26,2026-10-01 06:01:56,319.0,280.0,421.0
22,22,2026-10-01 06:02:26,2026-10-01 08:01:56,238.0,234.0,278.0
23,23,2026-10-01 08:02:26,2026-10-01 10:01:56,252.0,243.0,266.0
24,24,2026-10-01 10:02:26,2026-10-01 12:01:55,248.0,236.0,333.0
25,25,2026-10-01 12:02:25,2026-10-01 14:01:57,255.0,235.0,332.0
26,26,2026-10-01 14:02:27,2026-10-01 16:01:57,233.0,200.0,319.0
27,27,2026-10-01 16:02:27,2026-10-01 18:01:57,261.0,244.0,276.0
28,28,2026-10-01 18:02:27,2026-10-01 20:01:56,284.0,271.0,297.0
29,29,2026-10-01 20:02:26,2026-10-01 22:01:56,245.0,237.0,325.0
30,30,2026-10-01 22:02:26,2026-10-02 00:01:56,249.0,238.0,265.0
31,31,2026-10-02 00:02:26,2026-10-02 02:01:56,277.0,264.0,291.0
32,32,2026-10-02 02:02:26,2026-10-02 04:01:56,300.0,275.0,341.0
33,33,2026-10-02 04:02:26,2026-10-02 06:01:55,250.0,246.0,273.0
34,34,2026-10-02 06:02:25,2026-10-02 08:01:55,262.0,249.0,271.0
35,35,2026-10-02 08:02:25,2026-10-02 10:01:55,285.0,271.0,301.0
36,36,2026-10-02 10:02:25,2026-10-02 12:01:55,301.0,217.0,358.0
37,37,2026-10-02 12:02:25,2026-10-02 14:01:54,282.0,267.0,331.0
38,38,2026-10-02 14:02:24,2026-10-02 16:01:54,360.5,251.0,384.0
39,39,2026-10-02 16:02:24,2026-10-02 18:01:54,413.0,381.0,445.0
40,40,2026-10-02 18:02:24,2026-10-02 20:01:54,455.0,358.0,542.0
41,41,2026-10-02 20:02:24,2026-10-02 22:01:53,462.0,384.0,479.0
42,42,2026-10-02 22:02:23,2026-10-03 00:01:53,529.5,477.0,598.0
43,43,2026-10-03 00:02:23,2026-10-03 00:22:24,613.0,598.0,624.0

## 6. Model Preparation

A preliminary grouped split is prepared using provisional evidence-based labels.

In [41]:
# Prepare model dataset

model_df = df[
    candidate_features +
    ["freshness_label", "group_2h"]
].copy()

# Keep only rows with confirmed labels
labeled_df = model_df.dropna(
    subset=["freshness_label"]
).copy()

print("Total rows:", len(model_df))
print("Confirmed labeled rows:", len(labeled_df))

print("\nLabel distribution:")
print(labeled_df["freshness_label"].value_counts())

Total rows: 10465
Confirmed labeled rows: 544

Label distribution:
freshness_label
LOW       261
MEDIUM    242
HIGH       41
Name: count, dtype: int64

In [42]:
# Check labeled data before model preparation

print("Missing values in labeled data:\n")
print(labeled_df[candidate_features].isnull().sum())

print("\nFeature summary for confirmed labels:\n")

confirmed_feature_summary = (
    labeled_df
    .groupby("freshness_label")[candidate_features]
    .median()
    .round(2)
)

display(confirmed_feature_summary)

Missing values in labeled data:

storage_time_hours           0
storage_temp_c               0
air_temp_c                   0
humidity_pct                 0
temp_difference_c            0
lid_open_ratio               0
lid_open_rate_per_hour       0
avg_lid_open_duration_sec    0
gas_clean                    0
gas_rolling_median           0
dtype: int64

Feature summary for confirmed labels:

,storage_time_hours,storage_temp_c,air_temp_c,humidity_pct,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec,gas_clean,gas_rolling_median
freshness_label,,,,,,,,,,
HIGH,86.17,23.25,25.3,98.4,2.05,0.05,0.65,275.81,613.0,611.0
LOW,1.01,0.00,18.0,100.0,18.00,0.28,5.26,178.00,846.0,846.0
MEDIUM,58.99,0.00,14.8,79.9,14.50,0.06,0.69,302.71,245.0,245.0

In [43]:
# Create one feature summary row for each 2-hour temporal group

group_model_df = (
    df.groupby("group_2h")
      .agg(
          storage_time_hours=("storage_time_hours", "median"),
          storage_temp_c=("storage_temp_c", "median"),
          air_temp_c=("air_temp_c", "median"),
          humidity_pct=("humidity_pct", "median"),
          temp_difference_c=("temp_difference_c", "median"),
          lid_open_ratio=("lid_open_ratio", "median"),
          lid_open_rate_per_hour=("lid_open_rate_per_hour", "median"),
          avg_lid_open_duration_sec=("avg_lid_open_duration_sec", "median"),
          gas_clean=("gas_clean", "median"),
          gas_rolling_median=("gas_rolling_median", "median"),
          freshness_label=("freshness_label", "first")
      )
      .reset_index()
)

print("Total group-level rows:", len(group_model_df))
print("\nLabel distribution:")
print(group_model_df["freshness_label"].value_counts(dropna=False))

display(group_model_df.head(10))

Total group-level rows: 44

Label distribution:
freshness_label
None      41
LOW        1
MEDIUM     1
HIGH       1
Name: count, dtype: int64

,group_2h,storage_time_hours,storage_temp_c,air_temp_c,humidity_pct,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec,gas_clean,gas_rolling_median,freshness_label
0,0,1.00830,0.00,18.0,100.00,18.00,0.276684,5.26320,178.0000,846.0,846.0,LOW
1,1,2.99640,0.00,17.2,75.50,17.10,0.125429,3.86510,104.0770,858.0,858.0,None
2,2,5.00055,0.00,17.8,70.60,17.80,0.083520,2.59970,97.5000,868.5,868.0,None
3,3,7.00890,0.00,17.6,72.00,17.60,0.079264,1.99750,133.3330,881.0,881.0,None
4,4,9.00025,0.25,17.4,99.45,17.30,0.081386,1.73820,155.1175,890.0,889.5,None
5,5,11.02140,1.50,17.3,93.20,15.50,0.119344,1.62610,252.0560,880.0,883.0,None
6,6,13.00860,0.75,14.0,75.45,13.25,0.120732,1.55205,269.2380,799.5,800.0,None
7,7,15.00025,0.75,14.4,70.50,13.50,0.108424,1.40000,266.1360,798.0,798.0,None
8,8,17.00025,1.50,14.7,71.50,13.30,0.095668,1.23530,266.1360,800.0,799.0,None
9,9,19.01280,3.50,15.4,74.10,11.80,0.086397,1.12170,266.1360,807.0,807.0,None

In [44]:
# Check labeled temporal groups

labeled_groups = group_model_df.dropna(
    subset=["freshness_label"]
).copy()

print("Total temporal groups:", len(group_model_df))
print("Labeled temporal groups:", len(labeled_groups))
print("Unlabeled temporal groups:",
      group_model_df["freshness_label"].isna().sum())

print("\nLabeled groups:")
display(
    labeled_groups[
        ["group_2h", "freshness_label"]
    ]
)

Total temporal groups: 44
Labeled temporal groups: 3
Unlabeled temporal groups: 41

Labeled groups:

    group_2h freshness_label
0          0             LOW
29        29          MEDIUM
43        43            HIGH

In [45]:
# Create provisional labels for preliminary model development

df["model_label"] = pd.NA

# Conservative temporal windows around evidence-supported checkpoints
label_windows = {
    "LOW": [0, 1, 2],
    "MEDIUM": [28, 29, 30],
    "HIGH": [41, 42, 43]
}

for label, groups in label_windows.items():
    df.loc[
        df["group_2h"].isin(groups),
        "model_label"
    ] = label

print("Provisional label distribution:")
print(df["model_label"].value_counts(dropna=False))

print("\nTemporal groups used for each class:")
for label in ["LOW", "MEDIUM", "HIGH"]:
    groups = sorted(
        df.loc[df["model_label"] == label, "group_2h"].unique()
    )
    print(label, ":", groups)

Provisional label distribution:
model_label
<NA>      8474
LOW        746
MEDIUM     724
HIGH       521
Name: count, dtype: int64

Temporal groups used for each class:
LOW : [np.int64(0), np.int64(1), np.int64(2)]
MEDIUM : [np.int64(28), np.int64(29), np.int64(30)]
HIGH : [np.int64(41), np.int64(42), np.int64(43)]

In [46]:
# Split whole temporal groups into Train, Validation, and Test sets

import numpy as np

rng = np.random.default_rng(42)

train_groups = []
val_groups = []
test_groups = []

for label in ["LOW", "MEDIUM", "HIGH"]:

    groups = (
        df.loc[df["model_label"] == label, "group_2h"]
        .drop_duplicates()
        .to_numpy()
    )

    groups = rng.permutation(groups)

    train_groups.append(groups[0])
    val_groups.append(groups[1])
    test_groups.append(groups[2])


print("Train groups:", train_groups)
print("Validation groups:", val_groups)
print("Test groups:", test_groups)

Train groups: [np.int64(2), np.int64(28), np.int64(42)]
Validation groups: [np.int64(1), np.int64(30), np.int64(43)]
Test groups: [np.int64(0), np.int64(29), np.int64(41)]

In [47]:
# Create row-level Train, Validation, and Test datasets

train_df = df[
    df["group_2h"].isin(train_groups) &
    df["model_label"].notna()
].copy()

val_df = df[
    df["group_2h"].isin(val_groups) &
    df["model_label"].notna()
].copy()

test_df = df[
    df["group_2h"].isin(test_groups) &
    df["model_label"].notna()
].copy()


print("Train rows:", len(train_df))
print("Validation rows:", len(val_df))
print("Test rows:", len(test_df))

print("\nTrain labels:")
print(train_df["model_label"].value_counts())

print("\nValidation labels:")
print(val_df["model_label"].value_counts())

print("\nTest labels:")
print(test_df["model_label"].value_counts())

Train rows: 724
Validation rows: 524
Test rows: 743

Train labels:
model_label
LOW       244
MEDIUM    240
HIGH      240
Name: count, dtype: int64

Validation labels:
model_label
MEDIUM    242
LOW       241
HIGH       41
Name: count, dtype: int64

Test labels:
model_label
LOW       261
MEDIUM    242
HIGH      240
Name: count, dtype: int64