<a href="https://colab.research.google.com/github/Bhagya-Navodyani/Intelligent_Fish_Storage-ML/blob/main/notebook/Fish_Storage_ML_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# CSV file already uploaded to Colab
filename = "/content/Final_csv.csv"

# Read CSV
df_raw = pd.read_csv(filename)

print("Uploaded file:", filename)
print("Rows, Columns:", df_raw.shape)

print("\nColumns:")
print(df_raw.columns.tolist())

df_raw.head()

Uploaded file: /content/Final_csv.csv
Rows, Columns: (10465, 20)

Columns:
['pc_timestamp', 'trial_id', 'fish_species', 'record_type', 'elapsed_sec', 'storage_temp_c', 'air_temp_c', 'humidity_pct', 'distance_cm', 'gas_raw', 'reed_raw', 'lid', 'current_lid_open_sec', 'total_lid_open_sec', 'lid_open_count', 'storage_time_hours', 'temp_difference_c', 'lid_open_ratio', 'lid_open_rate_per_hour', 'avg_lid_open_duration_sec']

,pc_timestamp,trial_id,fish_species,record_type,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,lid,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
0,2026-09-29 10:02:23,TRIAL_20260929_100223,Linna,START,0,0.25,28.5,84.8,28.37,835,0,OPEN,0,0,1,0.0000,28.25,0.0,0.0,0.0
1,2026-09-29 10:02:53,TRIAL_20260929_100223,Linna,PERIODIC,30,0.25,28.3,84.1,28.38,835,0,OPEN,30,30,1,0.0083,28.05,1.0,0.0,30.0
2,2026-09-29 10:03:23,TRIAL_20260929_100223,Linna,PERIODIC,60,0.25,28.2,86.0,28.38,835,0,OPEN,60,60,1,0.0167,27.95,1.0,0.0,60.0
3,2026-09-29 10:03:53,TRIAL_20260929_100223,Linna,PERIODIC,90,0.25,28.1,86.0,28.37,835,0,OPEN,90,90,1,0.0250,27.85,1.0,0.0,90.0
4,2026-09-29 10:04:23,TRIAL_20260929_100223,Linna,PERIODIC,120,0.25,28.0,86.4,29.26,835,0,OPEN,120,120,1,0.0333,27.75,1.0,0.0,120.0

In [ ]:
# Make a separate preprocessing copy
df = df_raw.copy()

# Convert timestamp column to datetime
df["pc_timestamp"] = pd.to_datetime(
    df["pc_timestamp"],
    errors="coerce"
)

# Sort data by time
df = df.sort_values("pc_timestamp").reset_index(drop=True)

print("Total rows:", len(df))
print("Total columns:", len(df.columns))

print("\nMissing values in each column:")
print(df.isnull().sum())

print("\nFirst timestamp:", df["pc_timestamp"].min())
print("Last timestamp :", df["pc_timestamp"].max())

df.head()

Total rows: 10465
Total columns: 20

Missing values in each column:
pc_timestamp                   0
trial_id                       0
fish_species                   0
record_type                    0
elapsed_sec                    0
storage_temp_c                 0
air_temp_c                     0
humidity_pct                   0
distance_cm                  311
gas_raw                        0
reed_raw                       0
lid                            0
current_lid_open_sec           0
total_lid_open_sec             0
lid_open_count                 0
storage_time_hours             0
temp_difference_c              0
lid_open_ratio                 0
lid_open_rate_per_hour         0
avg_lid_open_duration_sec      0
dtype: int64

First timestamp: 2026-09-29 10:02:23
Last timestamp : 2026-10-03 00:22:24

,pc_timestamp,trial_id,fish_species,record_type,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,lid,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
0,2026-09-29 10:02:23,TRIAL_20260929_100223,Linna,START,0,0.25,28.5,84.8,28.37,835,0,OPEN,0,0,1,0.0000,28.25,0.0,0.0,0.0
1,2026-09-29 10:02:53,TRIAL_20260929_100223,Linna,PERIODIC,30,0.25,28.3,84.1,28.38,835,0,OPEN,30,30,1,0.0083,28.05,1.0,0.0,30.0
2,2026-09-29 10:03:23,TRIAL_20260929_100223,Linna,PERIODIC,60,0.25,28.2,86.0,28.38,835,0,OPEN,60,60,1,0.0167,27.95,1.0,0.0,60.0
3,2026-09-29 10:03:53,TRIAL_20260929_100223,Linna,PERIODIC,90,0.25,28.1,86.0,28.37,835,0,OPEN,90,90,1,0.0250,27.85,1.0,0.0,90.0
4,2026-09-29 10:04:23,TRIAL_20260929_100223,Linna,PERIODIC,120,0.25,28.0,86.4,29.26,835,0,OPEN,120,120,1,0.0333,27.75,1.0,0.0,120.0