<a href="https://colab.research.google.com/github/Bhagya-Navodyani/Intelligent_Fish_Storage-ML/blob/main/notebook/Fish_Storage_ML_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Dataset Loading

# Intelligent Fish Storage ML Pipeline

**Research Section:** Intelligent Fish Storage Quality Monitoring and Remaining Shelf-Life Prediction Using IoT and Machine Learning

This notebook contains the preprocessing and machine learning workflow for sensor data collected using the ESP32-S3 fish-storage monitoring prototype.

In [42]:
import pandas as pd
import numpy as np

# CSV file already uploaded to Colab
filename = "/content/Final_csv.csv"

# Read CSV
df_raw = pd.read_csv(filename)

print("Uploaded file:", filename)
print("Rows, Columns:", df_raw.shape)

print("\nColumns:")
print(df_raw.columns.tolist())

df_raw.head()

Uploaded file: /content/Final_csv.csv
Rows, Columns: (10465, 20)

Columns:
['pc_timestamp', 'trial_id', 'fish_species', 'record_type', 'elapsed_sec', 'storage_temp_c', 'air_temp_c', 'humidity_pct', 'distance_cm', 'gas_raw', 'reed_raw', 'lid', 'current_lid_open_sec', 'total_lid_open_sec', 'lid_open_count', 'storage_time_hours', 'temp_difference_c', 'lid_open_ratio', 'lid_open_rate_per_hour', 'avg_lid_open_duration_sec']

,pc_timestamp,trial_id,fish_species,record_type,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,lid,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
0,2026-09-29 10:02:23,TRIAL_20260929_100223,Linna,START,0,0.25,28.5,84.8,28.37,835,0,OPEN,0,0,1,0.0000,28.25,0.0,0.0,0.0
1,2026-09-29 10:02:53,TRIAL_20260929_100223,Linna,PERIODIC,30,0.25,28.3,84.1,28.38,835,0,OPEN,30,30,1,0.0083,28.05,1.0,0.0,30.0
2,2026-09-29 10:03:23,TRIAL_20260929_100223,Linna,PERIODIC,60,0.25,28.2,86.0,28.38,835,0,OPEN,60,60,1,0.0167,27.95,1.0,0.0,60.0
3,2026-09-29 10:03:53,TRIAL_20260929_100223,Linna,PERIODIC,90,0.25,28.1,86.0,28.37,835,0,OPEN,90,90,1,0.0250,27.85,1.0,0.0,90.0
4,2026-09-29 10:04:23,TRIAL_20260929_100223,Linna,PERIODIC,120,0.25,28.0,86.4,29.26,835,0,OPEN,120,120,1,0.0333,27.75,1.0,0.0,120.0

## 2. Dataset Audit

In [43]:
# Create a working copy while preserving the loaded dataset
df = df_raw.copy()

# Convert timestamp to datetime format
df["pc_timestamp"] = pd.to_datetime(
    df["pc_timestamp"],
    errors="coerce"
)

# Sort records chronologically
df = df.sort_values("pc_timestamp").reset_index(drop=True)

# Dataset summary
print("Total rows:", len(df))
print("Total columns:", len(df.columns))

print("\nMissing values in each column:")
print(df.isnull().sum())

print("\nFirst timestamp:", df["pc_timestamp"].min())
print("Last timestamp :", df["pc_timestamp"].max())

display(df.head())

Total rows: 10465
Total columns: 20

Missing values in each column:
pc_timestamp                   0
trial_id                       0
fish_species                   0
record_type                    0
elapsed_sec                    0
storage_temp_c                 0
air_temp_c                     0
humidity_pct                   0
distance_cm                  311
gas_raw                        0
reed_raw                       0
lid                            0
current_lid_open_sec           0
total_lid_open_sec             0
lid_open_count                 0
storage_time_hours             0
temp_difference_c              0
lid_open_ratio                 0
lid_open_rate_per_hour         0
avg_lid_open_duration_sec      0
dtype: int64

First timestamp: 2026-09-29 10:02:23
Last timestamp : 2026-10-03 00:22:24

,pc_timestamp,trial_id,fish_species,record_type,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,lid,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
0,2026-09-29 10:02:23,TRIAL_20260929_100223,Linna,START,0,0.25,28.5,84.8,28.37,835,0,OPEN,0,0,1,0.0000,28.25,0.0,0.0,0.0
1,2026-09-29 10:02:53,TRIAL_20260929_100223,Linna,PERIODIC,30,0.25,28.3,84.1,28.38,835,0,OPEN,30,30,1,0.0083,28.05,1.0,0.0,30.0
2,2026-09-29 10:03:23,TRIAL_20260929_100223,Linna,PERIODIC,60,0.25,28.2,86.0,28.38,835,0,OPEN,60,60,1,0.0167,27.95,1.0,0.0,60.0
3,2026-09-29 10:03:53,TRIAL_20260929_100223,Linna,PERIODIC,90,0.25,28.1,86.0,28.37,835,0,OPEN,90,90,1,0.0250,27.85,1.0,0.0,90.0
4,2026-09-29 10:04:23,TRIAL_20260929_100223,Linna,PERIODIC,120,0.25,28.0,86.4,29.26,835,0,OPEN,120,120,1,0.0333,27.75,1.0,0.0,120.0

In [44]:
# Check exact duplicate rows
duplicate_count = df.duplicated().sum()

print("Exact duplicate rows:", duplicate_count)

# Display basic numerical statistics
display(df.describe())

Exact duplicate rows: 0

,pc_timestamp,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
count,10465,10465.000000,10465.000000,10465.000000,10465.000000,10154.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000
mean,2026-10-01 05:07:33.561681664,155110.561682,1.828822,17.700554,81.426393,29.699733,473.731295,0.944386,19.286670,9724.143717,35.257047,43.086266,15.871732,0.080273,1.124134,265.053454
min,2026-09-29 10:02:23,0.000000,-0.250000,13.000000,57.400000,4.720000,200.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.900000,0.000000,0.000000,0.000000
25%,2026-09-30 07:29:29,77226.000000,0.000000,15.300000,73.300000,27.870000,275.000000,1.000000,0.000000,6551.000000,26.000000,21.451700,13.800000,0.054727,0.679600,266.136000
50%,2026-10-01 05:06:26,155043.000000,0.500000,17.300000,80.000000,28.710000,393.000000,1.000000,0.000000,10981.000000,37.000000,43.067500,15.650000,0.070716,0.837200,275.807000
75%,2026-10-02 02:48:26,233163.000000,1.500000,19.300000,89.200000,30.410000,627.000000,1.000000,0.000000,12762.000000,43.000000,64.767500,17.600000,0.080717,1.127900,296.784000
max,2026-10-03 00:22:24,310801.000000,23.500000,28.500000,100.000000,63.830000,1761.000000,1.000000,2278.000000,15721.000000,57.000000,86.333600,28.250000,1.000000,6.818200,630.000000
std,NaN,89930.812406,3.498060,3.010103,9.844427,3.760690,234.341593,0.229186,129.840186,4112.439112,12.845562,24.980780,3.476105,0.065577,0.872750,53.509667

### Initial Audit Findings

- The dataset contains 10,465 sensor observations.
- No exact duplicate rows were detected.
- The records are arranged chronologically using `pc_timestamp`.
- The `distance_cm` feature contains 311 missing values.
- The storage-temperature and gas-sensor columns require further anomaly investigation before model training.
- Sensor-quality issues will be handled during the preprocessing stage without modifying the original dataset.

In [45]:
# Check important sensor anomalies

zero_temp_count = (df["storage_temp_c"] == 0).sum()
high_gas_count = (df["gas_raw"] > 1000).sum()
missing_distance_count = df["distance_cm"].isnull().sum()

print("storage_temp_c = 0 rows:", zero_temp_count)
print("gas_raw > 1000 rows:", high_gas_count)
print("Missing distance_cm rows:", missing_distance_count)

storage_temp_c = 0 rows: 3128
gas_raw > 1000 rows: 14
Missing distance_cm rows: 311

## 3. Data Preprocessing

This section prepares the audited sensor dataset for machine learning while preserving the original measurements and documenting each preprocessing step.

### 3.1 Handling Missing Distance Measurements

Missing `distance_cm` values are handled in a separate cleaned feature while preserving the original measurements.

In [46]:
# Preserve the original distance measurements
df["distance_cm_clean"] = df["distance_cm"].copy()

# Interpolate missing values using neighboring time-series observations
df["distance_cm_clean"] = (
    df["distance_cm_clean"]
    .interpolate(method="linear")
    .bfill()
    .ffill()
)

print("Original missing distance values:",
      df["distance_cm"].isnull().sum())

print("Missing values after preprocessing:",
      df["distance_cm_clean"].isnull().sum())

Original missing distance values: 311
Missing values after preprocessing: 0

### 3.2 Storage Temperature Anomaly Investigation

The dataset contains a large number of zero values in `storage_temp_c`.
These readings are investigated before preprocessing to determine whether they represent valid near-ice temperatures or a sensor/wiring issue.

In [47]:
# Identify zero storage-temperature readings

zero_temp = df[df["storage_temp_c"] == 0].copy()

print("Total zero-temperature rows:", len(zero_temp))

print("\nFirst zero-temperature readings:")
display(
    zero_temp[
        ["pc_timestamp", "elapsed_sec", "storage_temp_c", "air_temp_c"]
    ].head(10)
)

print("\nLast zero-temperature readings:")
display(
    zero_temp[
        ["pc_timestamp", "elapsed_sec", "storage_temp_c", "air_temp_c"]
    ].tail(10)
)

Total zero-temperature rows: 3128

First zero-temperature readings:

          pc_timestamp  elapsed_sec  storage_temp_c  air_temp_c
12 2026-09-29 10:08:23          360             0.0        27.5
17 2026-09-29 10:10:53          510             0.0        26.3
18 2026-09-29 10:11:23          540             0.0        26.1
19 2026-09-29 10:11:53          570             0.0        25.9
20 2026-09-29 10:12:23          600             0.0        25.8
21 2026-09-29 10:12:53          630             0.0        25.6
22 2026-09-29 10:12:55          632             0.0        25.6
23 2026-09-29 10:13:23          660             0.0        25.2
24 2026-09-29 10:13:53          690             0.0        24.7
25 2026-09-29 10:14:23          720             0.0        24.2

Last zero-temperature readings:

            pc_timestamp  elapsed_sec  storage_temp_c  air_temp_c
9506 2026-10-02 16:26:24       282241             0.0        19.9
9508 2026-10-02 16:27:24       282301             0.0        19.9
9510 2026-10-02 16:28:24       282361             0.0        19.9
9511 2026-10-02 16:28:54       282391             0.0        19.9
9517 2026-10-02 16:31:54       282571             0.0        20.0
9518 2026-10-02 16:32:24       282601             0.0        20.0
9521 2026-10-02 16:33:54       282691             0.0        20.1
9528 2026-10-02 16:37:24       282901             0.0        20.1
9533 2026-10-02 16:39:54       283051             0.0        20.2
9536 2026-10-02 16:41:24       283141             0.0        20.2

### Storage Temperature Investigation Findings

- A total of 3,128 zero storage-temperature readings were detected.
- The zero readings occur across multiple separate time segments rather than one single continuous period.
- Both isolated zero readings and longer zero-reading periods are present.
- Therefore, zero values are not automatically replaced during this stage.
- Additional context and neighboring measurements will be examined before defining a valid preprocessing rule.

In [48]:
# Re-create zero-temperature groups correctly

# 1. Mark rows where storage temperature is exactly zero
df["temp_is_zero"] = (df["storage_temp_c"] == 0).astype(int)

# 2. Create continuous segment IDs
df["temp_zero_group"] = (
    df["temp_is_zero"]
    .ne(df["temp_is_zero"].shift())
    .cumsum()
)

# 3. Create zero-segment summary
zero_segments = (
    df[df["temp_is_zero"] == 1]
    .groupby("temp_zero_group")
    .agg(
        start_time=("pc_timestamp", "first"),
        end_time=("pc_timestamp", "last"),
        start_elapsed=("elapsed_sec", "first"),
        end_elapsed=("elapsed_sec", "last"),
        rows=("storage_temp_c", "size")
    )
    .reset_index()
)

# 4. Calculate segment duration in minutes
zero_segments["duration_minutes"] = (
    zero_segments["end_elapsed"] -
    zero_segments["start_elapsed"]
) / 60

display(zero_segments.head())

,temp_zero_group,start_time,end_time,start_elapsed,end_elapsed,rows,duration_minutes
0,2,2026-09-29 10:08:23,2026-09-29 10:08:23,360,360,1,0.000000
1,4,2026-09-29 10:10:53,2026-09-29 10:23:23,510,1260,28,12.500000
2,6,2026-09-29 10:27:23,2026-09-29 10:27:53,1500,1530,2,0.500000
3,8,2026-09-29 10:29:23,2026-09-29 10:33:06,1620,1843,10,3.716667
4,10,2026-09-29 10:34:23,2026-09-29 11:05:53,1920,3810,67,31.500000

### Storage Temperature Anomaly Decision

Several zero-temperature periods persist continuously for long durations, including segments lasting more than two hours. These long flat-line sequences are treated as suspected sensor/wiring anomalies rather than automatically assuming that all zero readings represent true storage temperature.

The original `storage_temp_c` values are preserved. A separate validity flag will be used to distinguish suspected invalid readings from usable measurements. Long missing/faulty periods will not be replaced by arbitrary temperature values.

In [49]:
# Re-create zero-temperature groups correctly

# 1. Mark rows where storage temperature is exactly zero
df["temp_is_zero"] = (df["storage_temp_c"] == 0).astype(int)

# 2. Create continuous segment IDs
df["temp_zero_group"] = (
    df["temp_is_zero"]
    .ne(df["temp_is_zero"].shift())
    .cumsum()
)

# 3. Create zero-segment summary
zero_segments = (
    df[df["temp_is_zero"] == 1]
    .groupby("temp_zero_group")
    .agg(
        start_time=("pc_timestamp", "first"),
        end_time=("pc_timestamp", "last"),
        start_elapsed=("elapsed_sec", "first"),
        end_elapsed=("elapsed_sec", "last"),
        rows=("storage_temp_c", "size")
    )
    .reset_index()
)

# 4. Calculate segment duration in minutes
zero_segments["duration_minutes"] = (
    zero_segments["end_elapsed"] -
    zero_segments["start_elapsed"]
) / 60

display(zero_segments.head())

,temp_zero_group,start_time,end_time,start_elapsed,end_elapsed,rows,duration_minutes
0,2,2026-09-29 10:08:23,2026-09-29 10:08:23,360,360,1,0.000000
1,4,2026-09-29 10:10:53,2026-09-29 10:23:23,510,1260,28,12.500000
2,6,2026-09-29 10:27:23,2026-09-29 10:27:53,1500,1530,2,0.500000
3,8,2026-09-29 10:29:23,2026-09-29 10:33:06,1620,1843,10,3.716667
4,10,2026-09-29 10:34:23,2026-09-29 11:05:53,1920,3810,67,31.500000

In [50]:
# Preserve the original storage temperature
df["storage_temp_original_c"] = df["storage_temp_c"].copy()

# Create a quality flag
df["storage_temp_valid"] = 1

# Identify long zero flat-line segments (>= 5 minutes)
long_zero_groups = zero_segments.loc[
    zero_segments["duration_minutes"] >= 5,
    "temp_zero_group"
]

# Mark these periods as suspected invalid
df.loc[
    df["temp_zero_group"].isin(long_zero_groups),
    "storage_temp_valid"
] = 0

print(
    "Valid temperature rows:",
    (df["storage_temp_valid"] == 1).sum()
)

print(
    "Suspected invalid temperature rows:",
    (df["storage_temp_valid"] == 0).sum()
)

Valid temperature rows: 7822
Suspected invalid temperature rows: 2643

### 3.3 Gas Sensor Quality Investigation

The original `gas_raw` measurements are preserved without artificial replacement.

Potentially abnormal gas-sensor readings are investigated using their timestamps, surrounding measurements, and the known sensor-wiring issue before assigning any data-quality flag.

In [51]:
# Basic gas-sensor inspection

print("Gas minimum:", df["gas_raw"].min())
print("Gas maximum:", df["gas_raw"].max())
print("Gas mean:", round(df["gas_raw"].mean(), 2))
print("Gas median:", df["gas_raw"].median())

print("\nGas value quantiles:")
print(
    df["gas_raw"].quantile(
        [0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

high_gas_rows = df[df["gas_raw"] > 1000].copy()

print("\nRows with gas_raw > 1000:", len(high_gas_rows))

display(
    high_gas_rows[
        [
            "pc_timestamp",
            "elapsed_sec",
            "gas_raw",
            "storage_temp_c",
            "air_temp_c",
            "humidity_pct"
        ]
    ]
)

Gas minimum: 200
Gas maximum: 1761
Gas mean: 473.73
Gas median: 393.0

Gas value quantiles:
0.25    275.00
0.50    393.00
0.75    627.00
0.90    860.00
0.95    881.00
0.99    909.36
Name: gas_raw, dtype: float64

Rows with gas_raw > 1000: 14

,pc_timestamp,elapsed_sec,gas_raw,storage_temp_c,air_temp_c,humidity_pct
1391,2026-09-29 21:21:10,40727,1017,2.50,21.3,100.0
1395,2026-09-29 21:23:10,40847,1031,2.50,21.4,100.0
1422,2026-09-29 21:35:40,41597,1691,1.25,19.3,100.0
2405,2026-09-30 05:45:02,70959,1679,2.25,19.7,100.0
2406,2026-09-30 05:45:09,70966,1651,2.00,19.9,100.0
2407,2026-09-30 05:45:38,70995,1614,2.00,20.1,100.0
2408,2026-09-30 05:45:39,70996,1613,2.00,20.1,100.0
2413,2026-09-30 05:47:09,71086,1017,2.00,20.1,100.0
2427,2026-09-30 05:53:09,71446,1761,2.00,20.2,100.0
2432,2026-09-30 05:55:39,71596,1527,2.25,21.2,100.0
3372,2026-09-30 13:44:58,99755,1497,0.00,24.2,100.0
3376,2026-09-30 13:46:58,99875,1564,0.50,24.0,99.9
3377,2026-09-30 13:47:28,99905,1531,0.50,23.6,99.4
4332,2026-09-30 21:37:57,128134,1568,0.25,24.5,100.0

### Gas Sensor Quality Flagging

The original `gas_raw` measurements are preserved without modification.

Gas readings are not classified as faulty only because they exceed a numerical threshold. Instead, the known sensor-wiring issue is represented using a separate data-quality flag and segment label.

This avoids replacing or fabricating gas measurements while allowing invalid periods to be excluded from gas-based model features.

In [52]:
# Preserve original gas readings
df["gas_original"] = df["gas_raw"].copy()

# Default values
df["gas_valid"] = 1
df["gas_segment"] = "VALID"

# Example only:
# Replace these timestamps with the actual known faulty period
fault_start = pd.Timestamp("2026-09-30 05:45:00")
fault_end   = pd.Timestamp("2026-09-30 05:56:00")

fault_mask = (
    (df["pc_timestamp"] >= fault_start) &
    (df["pc_timestamp"] <= fault_end)
)

df.loc[fault_mask, "gas_valid"] = 0
df.loc[fault_mask, "gas_segment"] = "FAULT_SUSPECTED"

print("Valid gas rows:",
      (df["gas_valid"] == 1).sum())

print("Suspected invalid gas rows:",
      (df["gas_valid"] == 0).sum())

display(
    df.loc[fault_mask,
           ["pc_timestamp", "gas_raw", "gas_valid", "gas_segment"]]
)

Valid gas rows: 10437
Suspected invalid gas rows: 28

            pc_timestamp  gas_raw  gas_valid      gas_segment
2405 2026-09-30 05:45:02     1679          0  FAULT_SUSPECTED
2406 2026-09-30 05:45:09     1651          0  FAULT_SUSPECTED
2407 2026-09-30 05:45:38     1614          0  FAULT_SUSPECTED
2408 2026-09-30 05:45:39     1613          0  FAULT_SUSPECTED
2409 2026-09-30 05:46:09      763          0  FAULT_SUSPECTED
2410 2026-09-30 05:46:21      651          0  FAULT_SUSPECTED
2411 2026-09-30 05:46:39      725          0  FAULT_SUSPECTED
2412 2026-09-30 05:46:45      671          0  FAULT_SUSPECTED
2413 2026-09-30 05:47:09     1017          0  FAULT_SUSPECTED
2414 2026-09-30 05:47:39      887          0  FAULT_SUSPECTED
2415 2026-09-30 05:48:09      911          0  FAULT_SUSPECTED
2416 2026-09-30 05:48:39      654          0  FAULT_SUSPECTED
2417 2026-09-30 05:48:40      698          0  FAULT_SUSPECTED
2418 2026-09-30 05:49:06      859          0  FAULT_SUSPECTED
2419 2026-09-30 05:49:09      857          0  FAULT_SUSPECTED
2420 2026-09-30 05:49:39      878          0  FAULT_SUSPECTED
2421 2026-09-30 05:50:09      946          0  FAULT_SUSPECTED
2422 2026-09-30 05:50:39      917          0  FAULT_SUSPECTED
2423 2026-09-30 05:51:09      679          0  FAULT_SUSPECTED
2424 2026-09-30 05:51:39      695          0  FAULT_SUSPECTED
2425 2026-09-30 05:52:09      731          0  FAULT_SUSPECTED
2426 2026-09-30 05:52:39      923          0  FAULT_SUSPECTED
2427 2026-09-30 05:53:09     1761          0  FAULT_SUSPECTED
2428 2026-09-30 05:53:39      779          0  FAULT_SUSPECTED
2429 2026-09-30 05:54:09      795          0  FAULT_SUSPECTED
2430 2026-09-30 05:54:39      805          0  FAULT_SUSPECTED
2431 2026-09-30 05:55:09      628          0  FAULT_SUSPECTED
2432 2026-09-30 05:55:39     1527          0  FAULT_SUSPECTED

### Gas Sensor Quality Flagging Result

A known sensor-wiring fault period was identified using its timestamp range.

All gas measurements recorded within this interval were marked as `FAULT_SUSPECTED` using the `gas_valid` quality flag, while preserving the original `gas_raw` measurements.

No gas values were artificially replaced or corrected. Gas-based model features will later use only readings considered valid.

In [53]:
print(df["gas_segment"].value_counts())
print()

display(
    df[
        [
            "pc_timestamp",
            "gas_raw",
            "gas_valid",
            "gas_segment"
        ]
    ].tail(10)
)

gas_segment
VALID              10437
FAULT_SUSPECTED       28
Name: count, dtype: int64

             pc_timestamp  gas_raw  gas_valid gas_segment
10455 2026-10-03 00:17:53      620          1       VALID
10456 2026-10-03 00:18:23      619          1       VALID
10457 2026-10-03 00:18:53      620          1       VALID
10458 2026-10-03 00:19:23      621          1       VALID
10459 2026-10-03 00:19:53      622          1       VALID
10460 2026-10-03 00:20:23      622          1       VALID
10461 2026-10-03 00:20:53      622          1       VALID
10462 2026-10-03 00:21:23      623          1       VALID
10463 2026-10-03 00:21:53      623          1       VALID
10464 2026-10-03 00:22:24      624          1       VALID

### 3.4 Gas Feature Engineering

Two simple gas-derived features are created for machine learning.

- `gas_delta` represents the change in gas level relative to the initial valid baseline.
- `gas_rolling_median` represents the recent gas level while reducing short sensor spikes and noise.

Only valid gas measurements are used. Fault-suspected readings are not artificially replaced.

In [54]:
# Create an ML-use gas column
df["gas_ml"] = df["gas_raw"].astype(float)

# Fault-suspected readings are excluded from gas-based features
df.loc[df["gas_valid"] == 0, "gas_ml"] = np.nan


# Gas baseline
# Use valid readings from the first 30 minutes


baseline_mask = (
    (df["elapsed_sec"] < 1800) &
    (df["gas_valid"] == 1)
)

gas_baseline = df.loc[baseline_mask, "gas_raw"].median()

print("Gas baseline:", gas_baseline)


# Gas delta


df["gas_delta"] = df["gas_ml"] - gas_baseline


# Trailing rolling median
# 5 readings ≈ 2.5 minutes for ~30-second sampling


df["gas_rolling_median"] = (
    df["gas_ml"]
    .rolling(window=5, min_periods=1)
    .median()
)

display(
    df[
        [
            "pc_timestamp",
            "gas_raw",
            "gas_valid",
            "gas_delta",
            "gas_rolling_median"
        ]
    ].head(20)
)

Gas baseline: 838.0

          pc_timestamp  gas_raw  gas_valid  gas_delta  gas_rolling_median
0  2026-09-29 10:02:23      835          1       -3.0               835.0
1  2026-09-29 10:02:53      835          1       -3.0               835.0
2  2026-09-29 10:03:23      835          1       -3.0               835.0
3  2026-09-29 10:03:53      835          1       -3.0               835.0
4  2026-09-29 10:04:23      835          1       -3.0               835.0
5  2026-09-29 10:04:53      835          1       -3.0               835.0
6  2026-09-29 10:05:23      835          1       -3.0               835.0
7  2026-09-29 10:05:53      835          1       -3.0               835.0
8  2026-09-29 10:06:23      835          1       -3.0               835.0
9  2026-09-29 10:06:53      835          1       -3.0               835.0
10 2026-09-29 10:07:23      836          1       -2.0               835.0
11 2026-09-29 10:07:53      836          1       -2.0               835.0
12 2026-09-29 10:08:23      836          1       -2.0               836.0
13 2026-09-29 10:08:53      835          1       -3.0               836.0
14 2026-09-29 10:09:23      836          1       -2.0               836.0
15 2026-09-29 10:09:53      835          1       -3.0               836.0
16 2026-09-29 10:10:23      836          1       -2.0               836.0
17 2026-09-29 10:10:53      836          1       -2.0               836.0
18 2026-09-29 10:11:23      836          1       -2.0               836.0
19 2026-09-29 10:11:53      836          1       -2.0               836.0

In [55]:
# Ensure fault-suspected gas periods are not used
# in derived gas features

invalid_gas_mask = df["gas_valid"] == 0

df.loc[invalid_gas_mask, "gas_delta"] = np.nan
df.loc[invalid_gas_mask, "gas_rolling_median"] = np.nan

print(
    "Missing gas_delta values:",
    df["gas_delta"].isnull().sum()
)

print(
    "Missing gas_rolling_median values:",
    df["gas_rolling_median"].isnull().sum()
)

display(
    df.loc[
        invalid_gas_mask,
        [
            "pc_timestamp",
            "gas_raw",
            "gas_valid",
            "gas_delta",
            "gas_rolling_median"
        ]
    ].head(10)
)

Missing gas_delta values: 28
Missing gas_rolling_median values: 28

            pc_timestamp  gas_raw  gas_valid  gas_delta  gas_rolling_median
2405 2026-09-30 05:45:02     1679          0        NaN                 NaN
2406 2026-09-30 05:45:09     1651          0        NaN                 NaN
2407 2026-09-30 05:45:38     1614          0        NaN                 NaN
2408 2026-09-30 05:45:39     1613          0        NaN                 NaN
2409 2026-09-30 05:46:09      763          0        NaN                 NaN
2410 2026-09-30 05:46:21      651          0        NaN                 NaN
2411 2026-09-30 05:46:39      725          0        NaN                 NaN
2412 2026-09-30 05:46:45      671          0        NaN                 NaN
2413 2026-09-30 05:47:09     1017          0        NaN                 NaN
2414 2026-09-30 05:47:39      887          0        NaN                 NaN

In [56]:

# Create ML-use storage temperature feature


# Preserve valid temperature readings only
df["storage_temp_ml_c"] = df["storage_temp_c"].astype(float)

# Suspected invalid temperature periods are not used
df.loc[
    df["storage_temp_valid"] == 0,
    "storage_temp_ml_c"
] = np.nan

# Recalculate temperature difference using the ML-use
# storage-temperature feature
df["temp_difference_ml_c"] = (
    df["air_temp_c"] - df["storage_temp_ml_c"]
)

print(
    "Missing storage_temp_ml_c values:",
    df["storage_temp_ml_c"].isnull().sum()
)

print(
    "Missing temp_difference_ml_c values:",
    df["temp_difference_ml_c"].isnull().sum()
)

Missing storage_temp_ml_c values: 2643
Missing temp_difference_ml_c values: 2643

In [57]:
candidate_features = [
    "storage_time_hours",
    "storage_temp_ml_c",
    "air_temp_c",
    "humidity_pct",
    "distance_cm",
    "temp_difference_ml_c",
    "lid_open_ratio",
    "lid_open_rate_per_hour",
    "avg_lid_open_duration_sec",
    "gas_delta",
    "gas_rolling_median"
]

print("Candidate ML features:\n")

for feature in candidate_features:
    print("-", feature)

print("\nMissing values in candidate features:\n")
print(df[candidate_features].isnull().sum())

Candidate ML features:

- storage_time_hours
- storage_temp_ml_c
- air_temp_c
- humidity_pct
- distance_cm
- temp_difference_ml_c
- lid_open_ratio
- lid_open_rate_per_hour
- avg_lid_open_duration_sec
- gas_delta
- gas_rolling_median

Missing values in candidate features:

storage_time_hours              0
storage_temp_ml_c            2643
air_temp_c                      0
humidity_pct                    0
distance_cm                   311
temp_difference_ml_c         2643
lid_open_ratio                  0
lid_open_rate_per_hour          0
avg_lid_open_duration_sec       0
gas_delta                      28
gas_rolling_median             28
dtype: int64

## 4. Time-Block Preparation

Because consecutive sensor readings are highly correlated, individual rows are not randomly split into training, validation, and testing sets.

The continuous time-series is first divided into 30-minute blocks. Four consecutive 30-minute blocks are then combined into one non-overlapping 2-hour temporal group.

These whole temporal groups will later be randomly assigned to the training, validation, and testing sets after the ground-truth freshness labels are prepared.

In [58]:
# Create 30-minute temporal blocks
# 30 minutes = 1800 seconds

df["block_30min"] = (
    df["elapsed_sec"] // 1800
).astype(int)

# Combine every 4 consecutive 30-minute blocks
# into one 2-hour temporal group
df["group_2h"] = (
    df["block_30min"] // 4
).astype(int)

print("Total 30-minute blocks:", df["block_30min"].nunique())
print("Total 2-hour groups:", df["group_2h"].nunique())

display(
    df[
        [
            "pc_timestamp",
            "elapsed_sec",
            "block_30min",
            "group_2h"
        ]
    ].head(20)
)

Total 30-minute blocks: 173
Total 2-hour groups: 44

          pc_timestamp  elapsed_sec  block_30min  group_2h
0  2026-09-29 10:02:23            0            0         0
1  2026-09-29 10:02:53           30            0         0
2  2026-09-29 10:03:23           60            0         0
3  2026-09-29 10:03:53           90            0         0
4  2026-09-29 10:04:23          120            0         0
5  2026-09-29 10:04:53          150            0         0
6  2026-09-29 10:05:23          180            0         0
7  2026-09-29 10:05:53          210            0         0
8  2026-09-29 10:06:23          240            0         0
9  2026-09-29 10:06:53          270            0         0
10 2026-09-29 10:07:23          300            0         0
11 2026-09-29 10:07:53          330            0         0
12 2026-09-29 10:08:23          360            0         0
13 2026-09-29 10:08:53          390            0         0
14 2026-09-29 10:09:23          420            0         0
15 2026-09-29 10:09:53          450            0         0
16 2026-09-29 10:10:23          480            0         0
17 2026-09-29 10:10:53          510            0         0
18 2026-09-29 10:11:23          540            0         0
19 2026-09-29 10:11:53          570            0         0

In [59]:
# Summarize each 2-hour temporal group

group_summary = (
    df.groupby("group_2h")
    .agg(
        start_time=("pc_timestamp", "min"),
        end_time=("pc_timestamp", "max"),
        rows=("pc_timestamp", "size"),
        first_block=("block_30min", "min"),
        last_block=("block_30min", "max")
    )
    .reset_index()
)

display(group_summary.head(10))

print("Total temporal groups:", len(group_summary))

,group_2h,start_time,end_time,rows,first_block,last_block
0,0,2026-09-29 10:02:23,2026-09-29 12:01:53,261,0,3
1,1,2026-09-29 12:02:23,2026-09-29 14:02:10,241,4,7
2,2,2026-09-29 14:02:40,2026-09-29 16:02:10,244,8,11
3,3,2026-09-29 16:02:40,2026-09-29 18:02:10,242,12,15
4,4,2026-09-29 18:02:40,2026-09-29 20:02:10,242,16,19
5,5,2026-09-29 20:02:40,2026-09-29 22:02:09,247,20,23
6,6,2026-09-29 22:02:39,2026-09-30 00:02:09,242,24,27
7,7,2026-09-30 00:02:39,2026-09-30 02:02:09,240,28,31
8,8,2026-09-30 02:02:39,2026-09-30 04:02:09,240,32,35
9,9,2026-09-30 04:02:39,2026-09-30 06:01:59,243,36,39

Total temporal groups: 44

## 5. Ground-Truth Freshness Labeling

The deployed system is designed to operate using IoT sensor measurements only.

During model development, independent manual sensory assessments are used only to establish ground-truth freshness labels for supervised learning.

These assessments are not used as machine-learning input features. The trained model will predict fish deterioration using sensor-derived features such as storage temperature, air temperature, humidity, gas measurements, lid activity, and storage duration.

LOW, MEDIUM, and HIGH deterioration labels will therefore be assigned only where sufficient independent ground-truth evidence is available. Uncertain transition periods will not be assigned arbitrary labels.

### 5.1 Manual Freshness Assessment Checkpoints

Manual sensory assessments are used only as independent ground-truth references during model development.

The deployed system does not require a camera or manual assessment. Only IoT sensor measurements will be used as model inputs.

Freshness labels will be assigned only for time periods supported by actual recorded observations. Uncertain periods will remain unlabeled rather than being assigned arbitrary classes.

In [60]:
# Template for manually recorded ground-truth checkpoints

ground_truth = pd.DataFrame(columns=[
    "assessment_time",
    "appearance_score",
    "eye_score",
    "firmness_score",
    "odour_score",
    "total_score",
    "freshness_label",
    "notes"
])

ground_truth

Empty DataFrame
Columns: [assessment_time, appearance_score, eye_score, firmness_score, odour_score, total_score, freshness_label, notes]
Index: []