<a href="https://colab.research.google.com/github/Bhagya-Navodyani/Intelligent_Fish_Storage-ML/blob/main/notebook/Fish_Storage_ML_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Dataset Loading

# Intelligent Fish Storage ML Pipeline

**Research Section:** Intelligent Fish Storage Quality Monitoring and Remaining Shelf-Life Prediction Using IoT and Machine Learning

This notebook contains the preprocessing and machine learning workflow for sensor data collected using the ESP32-S3 fish-storage monitoring prototype.

In [42]:
import pandas as pd
import numpy as np

# CSV file already uploaded to Colab
filename = "/content/Final_csv.csv"

# Read CSV
df_raw = pd.read_csv(filename)

print("Uploaded file:", filename)
print("Rows, Columns:", df_raw.shape)

print("\nColumns:")
print(df_raw.columns.tolist())

df_raw.head()

Uploaded file: /content/Final_csv.csv
Rows, Columns: (10465, 20)

Columns:
['pc_timestamp', 'trial_id', 'fish_species', 'record_type', 'elapsed_sec', 'storage_temp_c', 'air_temp_c', 'humidity_pct', 'distance_cm', 'gas_raw', 'reed_raw', 'lid', 'current_lid_open_sec', 'total_lid_open_sec', 'lid_open_count', 'storage_time_hours', 'temp_difference_c', 'lid_open_ratio', 'lid_open_rate_per_hour', 'avg_lid_open_duration_sec']

,pc_timestamp,trial_id,fish_species,record_type,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,lid,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
0,2026-09-29 10:02:23,TRIAL_20260929_100223,Linna,START,0,0.25,28.5,84.8,28.37,835,0,OPEN,0,0,1,0.0000,28.25,0.0,0.0,0.0
1,2026-09-29 10:02:53,TRIAL_20260929_100223,Linna,PERIODIC,30,0.25,28.3,84.1,28.38,835,0,OPEN,30,30,1,0.0083,28.05,1.0,0.0,30.0
2,2026-09-29 10:03:23,TRIAL_20260929_100223,Linna,PERIODIC,60,0.25,28.2,86.0,28.38,835,0,OPEN,60,60,1,0.0167,27.95,1.0,0.0,60.0
3,2026-09-29 10:03:53,TRIAL_20260929_100223,Linna,PERIODIC,90,0.25,28.1,86.0,28.37,835,0,OPEN,90,90,1,0.0250,27.85,1.0,0.0,90.0
4,2026-09-29 10:04:23,TRIAL_20260929_100223,Linna,PERIODIC,120,0.25,28.0,86.4,29.26,835,0,OPEN,120,120,1,0.0333,27.75,1.0,0.0,120.0

## 2. Dataset Audit

In [43]:
# Create a working copy while preserving the loaded dataset
df = df_raw.copy()

# Convert timestamp to datetime format
df["pc_timestamp"] = pd.to_datetime(
    df["pc_timestamp"],
    errors="coerce"
)

# Sort records chronologically
df = df.sort_values("pc_timestamp").reset_index(drop=True)

# Dataset summary
print("Total rows:", len(df))
print("Total columns:", len(df.columns))

print("\nMissing values in each column:")
print(df.isnull().sum())

print("\nFirst timestamp:", df["pc_timestamp"].min())
print("Last timestamp :", df["pc_timestamp"].max())

display(df.head())

Total rows: 10465
Total columns: 20

Missing values in each column:
pc_timestamp                   0
trial_id                       0
fish_species                   0
record_type                    0
elapsed_sec                    0
storage_temp_c                 0
air_temp_c                     0
humidity_pct                   0
distance_cm                  311
gas_raw                        0
reed_raw                       0
lid                            0
current_lid_open_sec           0
total_lid_open_sec             0
lid_open_count                 0
storage_time_hours             0
temp_difference_c              0
lid_open_ratio                 0
lid_open_rate_per_hour         0
avg_lid_open_duration_sec      0
dtype: int64

First timestamp: 2026-09-29 10:02:23
Last timestamp : 2026-10-03 00:22:24

,pc_timestamp,trial_id,fish_species,record_type,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,lid,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
0,2026-09-29 10:02:23,TRIAL_20260929_100223,Linna,START,0,0.25,28.5,84.8,28.37,835,0,OPEN,0,0,1,0.0000,28.25,0.0,0.0,0.0
1,2026-09-29 10:02:53,TRIAL_20260929_100223,Linna,PERIODIC,30,0.25,28.3,84.1,28.38,835,0,OPEN,30,30,1,0.0083,28.05,1.0,0.0,30.0
2,2026-09-29 10:03:23,TRIAL_20260929_100223,Linna,PERIODIC,60,0.25,28.2,86.0,28.38,835,0,OPEN,60,60,1,0.0167,27.95,1.0,0.0,60.0
3,2026-09-29 10:03:53,TRIAL_20260929_100223,Linna,PERIODIC,90,0.25,28.1,86.0,28.37,835,0,OPEN,90,90,1,0.0250,27.85,1.0,0.0,90.0
4,2026-09-29 10:04:23,TRIAL_20260929_100223,Linna,PERIODIC,120,0.25,28.0,86.4,29.26,835,0,OPEN,120,120,1,0.0333,27.75,1.0,0.0,120.0

In [44]:
# Check exact duplicate rows
duplicate_count = df.duplicated().sum()

print("Exact duplicate rows:", duplicate_count)

# Display basic numerical statistics
display(df.describe())

Exact duplicate rows: 0

,pc_timestamp,elapsed_sec,storage_temp_c,air_temp_c,humidity_pct,distance_cm,gas_raw,reed_raw,current_lid_open_sec,total_lid_open_sec,lid_open_count,storage_time_hours,temp_difference_c,lid_open_ratio,lid_open_rate_per_hour,avg_lid_open_duration_sec
count,10465,10465.000000,10465.000000,10465.000000,10465.000000,10154.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000,10465.000000
mean,2026-10-01 05:07:33.561681664,155110.561682,1.828822,17.700554,81.426393,29.699733,473.731295,0.944386,19.286670,9724.143717,35.257047,43.086266,15.871732,0.080273,1.124134,265.053454
min,2026-09-29 10:02:23,0.000000,-0.250000,13.000000,57.400000,4.720000,200.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.900000,0.000000,0.000000,0.000000
25%,2026-09-30 07:29:29,77226.000000,0.000000,15.300000,73.300000,27.870000,275.000000,1.000000,0.000000,6551.000000,26.000000,21.451700,13.800000,0.054727,0.679600,266.136000
50%,2026-10-01 05:06:26,155043.000000,0.500000,17.300000,80.000000,28.710000,393.000000,1.000000,0.000000,10981.000000,37.000000,43.067500,15.650000,0.070716,0.837200,275.807000
75%,2026-10-02 02:48:26,233163.000000,1.500000,19.300000,89.200000,30.410000,627.000000,1.000000,0.000000,12762.000000,43.000000,64.767500,17.600000,0.080717,1.127900,296.784000
max,2026-10-03 00:22:24,310801.000000,23.500000,28.500000,100.000000,63.830000,1761.000000,1.000000,2278.000000,15721.000000,57.000000,86.333600,28.250000,1.000000,6.818200,630.000000
std,NaN,89930.812406,3.498060,3.010103,9.844427,3.760690,234.341593,0.229186,129.840186,4112.439112,12.845562,24.980780,3.476105,0.065577,0.872750,53.509667

### Initial Audit Findings

- The dataset contains 10,465 sensor observations.
- No exact duplicate rows were detected.
- The records are arranged chronologically using `pc_timestamp`.
- The `distance_cm` feature contains 311 missing values.
- The storage-temperature and gas-sensor columns require further anomaly investigation before model training.
- Sensor-quality issues will be handled during the preprocessing stage without modifying the original dataset.

In [61]:
# Check important sensor data characteristics

zero_temp_count = (df["storage_temp_c"] == 0).sum()
high_gas_count = (df["gas_raw"] > 1000).sum()
missing_distance_count = df["distance_cm"].isnull().sum()
missing_temp_count = df["storage_temp_c"].isnull().sum()

print("storage_temp_c = 0°C readings:", zero_temp_count)
print("Missing storage_temp_c readings:", missing_temp_count)
print("gas_raw > 1000 readings:", high_gas_count)
print("Missing distance_cm rows:", missing_distance_count)

storage_temp_c = 0°C readings: 3128
Missing storage_temp_c readings: 0
gas_raw > 1000 readings: 14
Missing distance_cm rows: 311

## 3. Data Preprocessing

This section prepares the audited sensor dataset for machine learning while preserving the original measurements and documenting each preprocessing step.

### 3.2 Storage Temperature Anomaly Investigation

In [63]:
# Identify zero storage-temperature readings

zero_temp = df[df["storage_temp_c"] == 0].copy()

print("Total zero-temperature rows:", len(zero_temp))

print("\nFirst zero-temperature readings:")
display(
    zero_temp[
        ["pc_timestamp", "elapsed_sec", "storage_temp_c", "air_temp_c"]
    ].head(10)
)

print("\nLast zero-temperature readings:")
display(
    zero_temp[
        ["pc_timestamp", "elapsed_sec", "storage_temp_c", "air_temp_c"]
    ].tail(10)
)

Total zero-temperature rows: 3128

First zero-temperature readings:

          pc_timestamp  elapsed_sec  storage_temp_c  air_temp_c
12 2026-09-29 10:08:23          360             0.0        27.5
17 2026-09-29 10:10:53          510             0.0        26.3
18 2026-09-29 10:11:23          540             0.0        26.1
19 2026-09-29 10:11:53          570             0.0        25.9
20 2026-09-29 10:12:23          600             0.0        25.8
21 2026-09-29 10:12:53          630             0.0        25.6
22 2026-09-29 10:12:55          632             0.0        25.6
23 2026-09-29 10:13:23          660             0.0        25.2
24 2026-09-29 10:13:53          690             0.0        24.7
25 2026-09-29 10:14:23          720             0.0        24.2

Last zero-temperature readings:

            pc_timestamp  elapsed_sec  storage_temp_c  air_temp_c
9506 2026-10-02 16:26:24       282241             0.0        19.9
9508 2026-10-02 16:27:24       282301             0.0        19.9
9510 2026-10-02 16:28:24       282361             0.0        19.9
9511 2026-10-02 16:28:54       282391             0.0        19.9
9517 2026-10-02 16:31:54       282571             0.0        20.0
9518 2026-10-02 16:32:24       282601             0.0        20.0
9521 2026-10-02 16:33:54       282691             0.0        20.1
9528 2026-10-02 16:37:24       282901             0.0        20.1
9533 2026-10-02 16:39:54       283051             0.0        20.2
9536 2026-10-02 16:41:24       283141             0.0        20.2

In [68]:
# Validate storage-temperature measurements

zero_temp_count = (df["storage_temp_c"] == 0).sum()
missing_temp_count = df["storage_temp_c"].isnull().sum()

print("Valid 0°C storage-temperature readings:", zero_temp_count)
print("Missing storage-temperature readings:", missing_temp_count)

Valid 0°C storage-temperature readings: 3128
Missing storage-temperature readings: 0

### 3.3 Gas Sensor Quality Investigation

Gas readings are checked for statistical outliers while preserving the original `gas_raw` values.

In [69]:
# Detect gas outliers using the IQR method

q1 = df["gas_raw"].quantile(0.25)
q3 = df["gas_raw"].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

gas_outlier_mask = (
    (df["gas_raw"] < lower_bound) |
    (df["gas_raw"] > upper_bound)
)

print("Gas Q1:", q1)
print("Gas Q3:", q3)
print("IQR:", iqr)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Gas outlier rows:", gas_outlier_mask.sum())

display(
    df.loc[
        gas_outlier_mask,
        ["pc_timestamp", "gas_raw"]
    ]
)

Gas Q1: 275.0
Gas Q3: 627.0
IQR: 352.0
Lower bound: -253.0
Upper bound: 1155.0
Gas outlier rows: 11

            pc_timestamp  gas_raw
1422 2026-09-29 21:35:40     1691
2405 2026-09-30 05:45:02     1679
2406 2026-09-30 05:45:09     1651
2407 2026-09-30 05:45:38     1614
2408 2026-09-30 05:45:39     1613
2427 2026-09-30 05:53:09     1761
2432 2026-09-30 05:55:39     1527
3372 2026-09-30 13:44:58     1497
3376 2026-09-30 13:46:58     1564
3377 2026-09-30 13:47:28     1531
4332 2026-09-30 21:37:57     1568

In [70]:
print("Raw gas mean:", df["gas_raw"].mean())
print(
    "Mean without statistical outliers:",
    df.loc[~gas_outlier_mask, "gas_raw"].mean()
)

Raw gas mean: 473.73129479216436
Mean without statistical outliers: 472.53701932274726

### Gas Sensor Preprocessing

Statistical gas outliers are excluded from gas-based ML features while preserving the original `gas_raw` measurements.

In [71]:
# Preserve original gas readings for ML preprocessing
df["gas_clean"] = df["gas_raw"].astype(float)

# Mark IQR-detected gas outliers as missing for ML use
df.loc[gas_outlier_mask, "gas_clean"] = np.nan

print("Original gas rows:", len(df))
print("Gas outliers excluded:", gas_outlier_mask.sum())
print("Valid gas values for ML:", df["gas_clean"].notna().sum())

Original gas rows: 10465
Gas outliers excluded: 11
Valid gas values for ML: 10454

### 3.4 Gas Feature Engineering

`gas_delta` measures change from the initial gas baseline, while `gas_rolling_median` reduces short-term sensor noise.

In [72]:
# Gas baseline from the first 30 minutes
baseline_mask = df["elapsed_sec"] < 1800

gas_baseline = df.loc[
    baseline_mask,
    "gas_clean"
].median()

print("Gas baseline:", gas_baseline)


# Change from baseline
df["gas_delta"] = df["gas_clean"] - gas_baseline


# Rolling median: 5 readings ≈ 2.5 minutes
df["gas_rolling_median"] = (
    df["gas_clean"]
    .rolling(window=5, min_periods=1)
    .median()
)

display(
    df[
        [
            "pc_timestamp",
            "gas_raw",
            "gas_clean",
            "gas_delta",
            "gas_rolling_median"
        ]
    ].head(20)
)

Gas baseline: 838.0

          pc_timestamp  gas_raw  gas_clean  gas_delta  gas_rolling_median
0  2026-09-29 10:02:23      835      835.0       -3.0               835.0
1  2026-09-29 10:02:53      835      835.0       -3.0               835.0
2  2026-09-29 10:03:23      835      835.0       -3.0               835.0
3  2026-09-29 10:03:53      835      835.0       -3.0               835.0
4  2026-09-29 10:04:23      835      835.0       -3.0               835.0
5  2026-09-29 10:04:53      835      835.0       -3.0               835.0
6  2026-09-29 10:05:23      835      835.0       -3.0               835.0
7  2026-09-29 10:05:53      835      835.0       -3.0               835.0
8  2026-09-29 10:06:23      835      835.0       -3.0               835.0
9  2026-09-29 10:06:53      835      835.0       -3.0               835.0
10 2026-09-29 10:07:23      836      836.0       -2.0               835.0
11 2026-09-29 10:07:53      836      836.0       -2.0               835.0
12 2026-09-29 10:08:23      836      836.0       -2.0               836.0
13 2026-09-29 10:08:53      835      835.0       -3.0               836.0
14 2026-09-29 10:09:23      836      836.0       -2.0               836.0
15 2026-09-29 10:09:53      835      835.0       -3.0               836.0
16 2026-09-29 10:10:23      836      836.0       -2.0               836.0
17 2026-09-29 10:10:53      836      836.0       -2.0               836.0
18 2026-09-29 10:11:23      836      836.0       -2.0               836.0
19 2026-09-29 10:11:53      836      836.0       -2.0               836.0

In [73]:
print("Missing gas_clean values:", df["gas_clean"].isnull().sum())
print("Missing gas_delta values:", df["gas_delta"].isnull().sum())
print("Missing gas_rolling_median values:", df["gas_rolling_median"].isnull().sum())

Missing gas_clean values: 11
Missing gas_delta values: 11
Missing gas_rolling_median values: 0

In [75]:
# Ensure gas outlier rows are excluded from gas-derived ML features
df.loc[gas_outlier_mask, "gas_delta"] = np.nan
df.loc[gas_outlier_mask, "gas_rolling_median"] = np.nan


candidate_features = [
    "storage_time_hours",
    "storage_temp_c",
    "air_temp_c",
    "humidity_pct",
    "temp_difference_c",
    "lid_open_ratio",
    "lid_open_rate_per_hour",
    "avg_lid_open_duration_sec",
    "gas_delta",
    "gas_rolling_median"
]

print("Candidate ML features:\n")

for feature in candidate_features:
    print("-", feature)

print("\nMissing values in candidate features:\n")
print(df[candidate_features].isnull().sum())

Candidate ML features:

- storage_time_hours
- storage_temp_c
- air_temp_c
- humidity_pct
- temp_difference_c
- lid_open_ratio
- lid_open_rate_per_hour
- avg_lid_open_duration_sec
- gas_delta
- gas_rolling_median

Missing values in candidate features:

storage_time_hours            0
storage_temp_c                0
air_temp_c                    0
humidity_pct                  0
temp_difference_c             0
lid_open_ratio                0
lid_open_rate_per_hour        0
avg_lid_open_duration_sec     0
gas_delta                    11
gas_rolling_median           11
dtype: int64

## 4. Time-Block Preparation

Because consecutive sensor readings are highly correlated, individual rows are not randomly split into training, validation, and testing sets.

The continuous time-series is first divided into 30-minute blocks. Four consecutive 30-minute blocks are then combined into one non-overlapping 2-hour temporal group.

These whole temporal groups will later be randomly assigned to the training, validation, and testing sets after the ground-truth freshness labels are prepared.

In [58]:
# Create 30-minute temporal blocks
# 30 minutes = 1800 seconds

df["block_30min"] = (
    df["elapsed_sec"] // 1800
).astype(int)

# Combine every 4 consecutive 30-minute blocks
# into one 2-hour temporal group
df["group_2h"] = (
    df["block_30min"] // 4
).astype(int)

print("Total 30-minute blocks:", df["block_30min"].nunique())
print("Total 2-hour groups:", df["group_2h"].nunique())

display(
    df[
        [
            "pc_timestamp",
            "elapsed_sec",
            "block_30min",
            "group_2h"
        ]
    ].head(20)
)

Total 30-minute blocks: 173
Total 2-hour groups: 44

          pc_timestamp  elapsed_sec  block_30min  group_2h
0  2026-09-29 10:02:23            0            0         0
1  2026-09-29 10:02:53           30            0         0
2  2026-09-29 10:03:23           60            0         0
3  2026-09-29 10:03:53           90            0         0
4  2026-09-29 10:04:23          120            0         0
5  2026-09-29 10:04:53          150            0         0
6  2026-09-29 10:05:23          180            0         0
7  2026-09-29 10:05:53          210            0         0
8  2026-09-29 10:06:23          240            0         0
9  2026-09-29 10:06:53          270            0         0
10 2026-09-29 10:07:23          300            0         0
11 2026-09-29 10:07:53          330            0         0
12 2026-09-29 10:08:23          360            0         0
13 2026-09-29 10:08:53          390            0         0
14 2026-09-29 10:09:23          420            0         0
15 2026-09-29 10:09:53          450            0         0
16 2026-09-29 10:10:23          480            0         0
17 2026-09-29 10:10:53          510            0         0
18 2026-09-29 10:11:23          540            0         0
19 2026-09-29 10:11:53          570            0         0

In [59]:
# Summarize each 2-hour temporal group

group_summary = (
    df.groupby("group_2h")
    .agg(
        start_time=("pc_timestamp", "min"),
        end_time=("pc_timestamp", "max"),
        rows=("pc_timestamp", "size"),
        first_block=("block_30min", "min"),
        last_block=("block_30min", "max")
    )
    .reset_index()
)

display(group_summary.head(10))

print("Total temporal groups:", len(group_summary))

,group_2h,start_time,end_time,rows,first_block,last_block
0,0,2026-09-29 10:02:23,2026-09-29 12:01:53,261,0,3
1,1,2026-09-29 12:02:23,2026-09-29 14:02:10,241,4,7
2,2,2026-09-29 14:02:40,2026-09-29 16:02:10,244,8,11
3,3,2026-09-29 16:02:40,2026-09-29 18:02:10,242,12,15
4,4,2026-09-29 18:02:40,2026-09-29 20:02:10,242,16,19
5,5,2026-09-29 20:02:40,2026-09-29 22:02:09,247,20,23
6,6,2026-09-29 22:02:39,2026-09-30 00:02:09,242,24,27
7,7,2026-09-30 00:02:39,2026-09-30 02:02:09,240,28,31
8,8,2026-09-30 02:02:39,2026-09-30 04:02:09,240,32,35
9,9,2026-09-30 04:02:39,2026-09-30 06:01:59,243,36,39

Total temporal groups: 44

## 5. Ground-Truth Freshness Labeling

Freshness labels will be assigned only using independently recorded ground-truth observations.

In [76]:
# Record only confirmed ground-truth observations

confirmed_ground_truth = pd.DataFrame({
    "stage": ["START", "END"],
    "condition": [
        "Fresh fish at the beginning of the experiment",
        "Fish showed clear spoilage at the end of the experiment"
    ],
    "deterioration_label": ["LOW", "HIGH"]
})

confirmed_ground_truth

,stage,condition,deterioration_label
0,START,Fresh fish at the beginning of the experiment,LOW
1,END,Fish showed clear spoilage at the end of the e...,HIGH

In [77]:
# Identify the first and last temporal groups

first_group = df["group_2h"].min()
last_group = df["group_2h"].max()

print("START temporal group:", first_group)
print("END temporal group:", last_group)

display(
    group_summary[
        group_summary["group_2h"].isin([first_group, last_group])
    ]
)

START temporal group: 0
END temporal group: 43

,group_2h,start_time,end_time,rows,first_block,last_block
0,0,2026-09-29 10:02:23,2026-09-29 12:01:53,261,0,3
43,43,2026-10-03 00:02:23,2026-10-03 00:22:24,41,172,172

In [78]:
# Create freshness-label column

df["freshness_label"] = pd.NA

# Confirmed fresh condition at the start
df.loc[
    df["group_2h"] == first_group,
    "freshness_label"
] = "LOW"

# Confirmed spoiled condition at the end
df.loc[
    df["group_2h"] == last_group,
    "freshness_label"
] = "HIGH"

print(df["freshness_label"].value_counts(dropna=False))

freshness_label
<NA>    10163
LOW       261
HIGH       41
Name: count, dtype: int64

In [79]:
# Check confirmed labeled groups

label_summary = (
    df.dropna(subset=["freshness_label"])
      .groupby(["group_2h", "freshness_label"])
      .agg(
          start_time=("pc_timestamp", "min"),
          end_time=("pc_timestamp", "max"),
          rows=("pc_timestamp", "size")
      )
      .reset_index()
)

display(label_summary)

   group_2h freshness_label          start_time            end_time  rows
0         0             LOW 2026-09-29 10:02:23 2026-09-29 12:01:53   261
1        43            HIGH 2026-10-03 00:02:23 2026-10-03 00:22:24    41

## 6. Model Preparation

Model training will begin after valid LOW, MEDIUM, and HIGH ground-truth labels are established.

In [80]:
# Prepare model dataset

model_df = df[
    candidate_features +
    ["freshness_label", "group_2h"]
].copy()

# Keep only rows with confirmed labels
labeled_df = model_df.dropna(
    subset=["freshness_label"]
).copy()

print("Total rows:", len(model_df))
print("Confirmed labeled rows:", len(labeled_df))

print("\nLabel distribution:")
print(labeled_df["freshness_label"].value_counts())

Total rows: 10465
Confirmed labeled rows: 302

Label distribution:
freshness_label
LOW     261
HIGH     41
Name: count, dtype: int64